language: cpp
sudo: false

notifications:
  recipients:
    - roberto.d.remigio@uit.no
    - luca.frediani@uit.no
  email:
    on_success: change
    on_failure: always

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "cxaDDZPFc1DJMa78/Sla/5TA5KUQ8e/Ig1zeXO9RbnEQUL3z7pmwgSEvg4l90x7AocdMQI2kzBYb7vbUM2fdH2+GtdCtttWIlPMPAxPJuwKvnhYXFJyXLpLWfxf2BmUovi54GN7lJ8pX/RTGkqqeAmaxIWzsPq5iiLSSOaan6sY="

addons: &gcc5
  apt:
    sources: ['ubuntu-toolchain-r-test', 'boost-latest']
    packages: ['g++-5', 'gcc-5', 'libboost1.55-all-dev', 'gfortran-5']
  coverity_scan:
    project:
      name: "PCMSolver/pcmsolver"
      version: 1.0.4
      description: "An API for the Polarizable Continuum Model "
    notification_email: roberto.d.remigio@uit.no
    build_command_prepend: "python setup.py --cxx=g++-5 --cc=gcc-5 --fc=gfortran-5 --type=debug; cd build"
    build_command: "make -j 2"
    branch_pattern: coverity_scan